### PR TITLE
feat/samba

### LINKED ISSUE #23: Samba

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #23

### CODE REVIEW

**Review by loicmathieu — COMMENTED** [review]
Can you explain why you add all those libraries inside the Gradle config and why it's not possible to use the standard common-vfs library?

Doing so will add maintenance cost as we would need to follow the changes upstream and do a release each time it's released upstream.

**Comment by brian-mulier-p** [comment]
I added some comments but I have no strong opinion on the commons-vfs2 fork, that was already on the branch from @tchiotludo but I think it was mostly for sandbox but as I no longer use that dependency maybe we should go back on that release :thinking:.
For the newly added lib I added a comment but basically commons-vfs2 doesn't offer SMB protocol handling (it's only part of their sandbox right now, AKA experimental features which are on another lib). However even that experimental handling from Apache doesn't support SMB2 / 3 while it's what's recommended security wise so I believe it won't be able to be used if we don't use another lib that handles that.
[The lib I added](https://github.com/new-proimage/vfs-jcifs-smb) provides an extra-layer over commons-vfs2's sandbox to add SMB2/3 support

**Comment by loicmathieu** [comment]
If sandbox is not needed, please use the official release

**Comment by brian-mulier-p** [comment]
Done

**Review by loicmathieu — APPROVED** [review]
LGTM

**Pull request merged**
